name: CI Publish, with security check using Snyk

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest
    continue-on-error: true  # ✅ Allow security failures without stopping other jobs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Set Snyk Authentication
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: echo "Snyk authentication set"

      - name: Run Snyk security check
        run: snyk test --severity-threshold=high
        continue-on-error: true  # ✅ This prevents security failures from blocking the build

  build:
    needs: [security]  # ✅ Will now run even if security has issues
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build --if-present

      - name: Run tests
        run: npm test

  publish:
    needs: [security, build]  # ✅ Will now run after both security and build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
